### ISSUE TITLE
BLOCKERAD Inloggning

### ISSUE THREAD

**Issue by mirvnillith** [mirvnillith/skvf-kaninregister#3]
Blockerad av #2 

Sida för inloggning:
- Inmatning av användarnamn och lösenord
- POST /login
- Hantera 401

**Comment by lobax** [comment]
Inloggning: 
https://github.com/mirvnillith/skvf-kaninregister/blob/feature/frontend/src/main/js/Login.js

POST /login, hantering av 401:
https://github.com/mirvnillith/skvf-kaninregister/blob/a2ca3cd55850432dd7a58a04fce8df83158c3918/src/main/js/utils/api.js#L57

**Comment by mirvnillith** [comment]
Jag behöver inte mer än att du känner dig klar. När vi har lite mer på plats ska vi väl fundera på någon enkel hosting så vi kan släppa in resten att köra igenom.
