### ISSUE TITLE
Kunna ange sig själv som uppfödare för ny kanin

### ISSUE THREAD

**Issue by mirvnillith** [mirvnillith/skvf-kaninregister#38]
När man registrerar en ny kanin ska man kunna ange att man själv är dess uppfödare.
(vid senare editering ska man kunna se uppfödaren, även andra än sig själv, och kunna tömma eller ange sig själv men inte andra)

**Comment by zugerto** [comment]
Jag kunde ange att jag var en ny kanins uppfödare och det sparades som kaninens uppfödare
