### ISSUE TITLE
Utloggning

### ISSUE THREAD

**Issue by mirvnillith** [mirvnillith/skvf-kaninregister#4]
Knapp för utloggning:
- POST /logout
- Åter till första sidan

**Comment by zugerto** [comment]
OK om jag börjar titta lite på denna?

**Comment by mirvnillith** [comment]
Verkar som om den inte längre är blockerad, ja.

**Comment by zugerto** [comment]
Jag dök på en liten frågeställning. Ska man kunna refresha sidan när man är inloggad och fortsätta vara inloggad? Den kaka som sätts ligger på /api. Annars är jag klar. Om man är inloggad får man en liten logga ut knapp uppe i högra hörnet och trycker man på den hamnar man på logga in-vyn.

**Comment by mirvnillith** [comment]
Vi borde behålla inloggningen, men det kanske kräver ändring hos ”mig”?
Tänkte inte på att URLn ingår.

mån 15 nov. 2021 kl. 09:31 skrev Marcus Ludvigsson ***@***.***

**Comment by zugerto** [comment]
Det går nog att lösa men jag måste nog veta namnet på kakan på klient-sidan. Om det finns en sådan kaka kan jag anta att jag är inloggad efter en refresh av sidan. Efterföljande operationer valideras ju av backend utifrån sessionsid.

**Comment by zugerto** [comment]
och lite annorlunda kaka. Men det kan jag laborera lite med.

**Comment by mirvnillith** [comment]
Du hittar säkert det i koden.

mån 15 nov. 2021 kl. 11:47 skrev Marcus Ludvigsson ***@***.***

**Comment by zugerto** [comment]
Nu finns det en knapp efter inloggning och klickar man på den blir man utloggad. Man kan göra en refresh av browsern utan att bli utloggad.
