### ISSUE TITLE
Icke-signering

### ISSUE THREAD

**Issue by mirvnillith** [mirvnillith/skvf-kaninregister#5]
Hantering av ingen GDPR-signering efter inloggning:
- skvf.approval.url är tom
- POST /owners/<ID>/approve
- Hantera 401, 404
- Gå vidare som inloggad

**Comment by zugerto** [comment]
Om skvf.approval.url är tom när man gör anropet till /owner/<id>/approve sätts signaturen till "-" och Void returneras vilket gör att 204 returneras vilket ska vara "Approval failed" enligt api-dokumentationen. Om man gör ett anrop till, nu med en valid signature får man också 204 tillbaka. Så 204 borde vara Owner approved.

**Comment by mirvnillith** [comment]
Annan default-hantering av Jersey än jag är van vid. main ska nu returnera 200 rätt.

**Comment by zugerto** [comment]
Nja, det lilla tricket fungerade inte. När Jersey upptäcker att den ska returnera Void sätter den returstatus till NO_CONTENT. Jag kör vidare med 204 ett tag..

**Comment by mirvnillith** [comment]
Då googlar jag …

fre 19 nov. 2021 kl. 21:36 skrev Marcus Ludvigsson ***@***.***

**Comment by mirvnillith** [comment]
Så, fick lura Jersey lite (nu med verifierande test)

Den fre 19 nov. 2021 kl 21:42 skrev Jonas Olsson ***@***.***>:

**Comment by zugerto** [comment]
Vad jag tror är denna samt förbättring av sessionhanteringen finns i PR
