### ISSUE TITLE
Se kontaktuppgifter när en kanin hittas

### ISSUE THREAD

**Issue by zugerto** [mirvnillith/skvf-kaninregister#70]
Roade mig med att testa genom lite nya flöden. 

När man vill se kontaktuppgifter när man hittat en kanin och ägaren av kaninen inte har klickat i "Synlig som ägare för användare av kaninregistret" så får man 204 från backend och "kontakter"-knappen fortsätter att snurra.

**Comment by mirvnillith** [comment]
Hm, trodde den kedjan (ägare, tidigare ägare och uppfödare) var säkrad nu.
Den är lite avancerad, tre laddningar efter varandra, men något snubblar
väl då. Står det något i konsollen?

mån 3 jan. 2022 kl. 11:05 skrev Marcus Ludvigsson ***@***.***

**Comment by zugerto** [comment]
det gjorde det:
 nonPublic is not defined
    at setBunnyOwner (FindForm.js:63)

**Comment by mirvnillith** [comment]
import { nonPublic } from ’../utils/data.js’

mån 3 jan. 2022 kl. 12:20 skrev Marcus Ludvigsson ***@***.***

**Comment by mirvnillith** [comment]
Fixat och deployat, på mobilen, på toaletten …

**Comment by zugerto** [comment]
Javascript, vilket fantastiskt språk..
jag kan ju tycka att detta borde hittas av ett byggsteg i alla fall

**Comment by zugerto** [comment]
Like a pro!
